"use strict";
exports.__esModule = true;
exports.locale = void 0;
var locale;
(function (locale) {
    locale["Ar"] = "ar";
    locale["Bg"] = "bg";
    locale["Bs"] = "bs";
    locale["Ca"] = "ca";
    locale["Cs"] = "cs";
    locale["Da"] = "da";
    locale["De"] = "de";
    locale["DeForm"] = "de-form";
    locale["El"] = "el";
    locale["En"] = "en";
    locale["Es"] = "es";
    locale["Et"] = "et";
    locale["Fi"] = "fi";
    locale["Fr"] = "fr";
    locale["He"] = "he";
    locale["Hr"] = "hr";
    locale["Hu"] = "hu";
    locale["Id"] = "id";
    locale["It"] = "it";
    locale["Ja"] = "ja";
    locale["Ko"] = "ko";
    locale["Lt"] = "lt";
    locale["Lv"] = "lv";
    locale["Mn"] = "mn";
    locale["Nb"] = "nb";
    locale["Nl"] = "nl";
    locale["Pl"] = "pl";
    locale["PtBR"] = "pt-BR";
    locale["Pt"] = "pt";
    locale["Ro"] = "ro";
    locale["Ru"] = "ru";
    locale["Sl"] = "sl";
    locale["Sr"] = "sr";
    locale["Sv"] = "sv";
    locale["Tr"] = "tr";
    locale["Vi"] = "vi";
    locale["ZhCN"] = "zh-CN";
    locale["ZhTW"] = "zh-TW";
})(locale = exports.locale || (exports.locale = {}));
